Task1 develop
Mr-S-Mirzoev/TechnoSphere-Task pull request #1
Opened 2020-10-07 21:35 UTC by Mr-S-Mirzoev

Task 1 being solved

2020-10-08 15:04 UTC, a-badin requested changes
Когда по методу close() у вас будут закрываться дескрипторы, проверьте что вы инвалидируйте их значения. Вот такой код не должен писать в файл tmp
```
    Process proc("/bin/cat");
    proc.close();
    std::ofstream f1{"tmp"};
    std::ofstream f2{"tmp"};

    std::string buf{"Unexpected behaviour"};
    proc.writeExact(buf.c_str(), buf.size());
```

2020-10-08 15:04 UTC, a-badin commented on 1. Process/CMakeLists.txt
> +target_compile_features(main PRIVATE cxx_std_17)
Так как мы во всем проекте будем  пользоваться  C++17 давайте один раз напишем `set(CMAKE_CXX_STANDARD 17)` после project, тогда это не надо будет описывать для каждой цели

2020-10-08 15:04 UTC, a-badin commented on 1. Process/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0)
CMAKE_CXX_STANDARD как и фича cxx_std_17 появился только в версии 3.8

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.hpp
> +#include <fcntl.h>
для объявления этого класса, вам не нужен ни один этот заголовок, кроме  #include <sys/types.h>. Лучше подключать только те заголовки, котороые необходимы для объявления класса

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.hpp
> +    int fd1[2];
после выхода из коструктора вам будет нужно держать только по 1 дескрипору от каждого пайпа, лучше назвать их осмысленно

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +std::vector<char*> Process::arg_list(const std::string &name, const std::vector <std::string>& args) {
И arg_list и exec_name скорее относятся к деталям реализации, учитывая что вы положили их как private. Тогда лучше объявить их тут как статическую глобальную функцию и не вносить её в класс.

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +    pipe2(fd1, 0);
нужно проверить, что нет ошибки

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +    if (!_pid) {
сюда можно попасть в случае если fork вернет ошибку, тогда программа провалится в exec

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +        dup2(fd1[0], 0);
Лучше не пользоваться магическими цифрами и воспользоваться константами STDIN_FILENO из <unistd.h>.

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +        signal(SIGINT, sig_handler);
нет смысла устанавливать обработчик сигналов, после exec все обработчики сбрасываются

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +    pid_t pid_result = waitpid(_pid, &status, WNOHANG);
Если pid_result не 0, то объект становится бесполезным - мы не можем ни переинициализировать его, ни пользоваться им. Я думаю лучше просто кинуть исключение, или вызвать ::exit

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +    size_t ret_val = ::read(fd2[0], data, len);
::read возвращает знаковый size_t , поэтому если ret_val меньше 0, то нужно кинуть исключение или ::exit. Вернуть число меньше 0 мы не можем

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +        size_t bytes_read = read(data + offset, len);
data нужно один раз кастануть в char*, потому что у char есть размер а у void нет.

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +    size_t ret_val = ::write(fd1[1], data, len);
тоже проверить ошибку

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +    if (_pid)
нужно закрыть все дескрипторы

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +    if (!_pid)
Нужно закрыть не свой stdin, а stdin дочернего процесса, то есть закрыть fd1[1]

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +        waitpid(_pid, NULL, 0);
Далеко не каждая программа закрывается, когда закрывается ее стандартный ввод - эта логика лишняя

2020-10-08 15:04 UTC, a-badin commented on 1. Process/process.cpp
> +    cstyle_args.reserve(args.size());
args.size() + 1

2020-10-08 16:24 UTC, Mr-S-Mirzoev commented on 1. Process/process.cpp
> +    if (!_pid) {
Обработки ошибки действительно не хватало, однако в exec он тоже не провалился. 

При ошибке в форке он возвращает -1, !(-1) = 0, что означало бы невыполнение условия ифа

2020-10-09 18:55 UTC, a-badin requested changes

2020-10-09 18:55 UTC, a-badin commented on 1. Process/process.hpp
> +static std::vector<char*> arg_list(const std::string &name, const std::vector <std::string>& args);
лучше убрать

2020-10-09 18:55 UTC, a-badin commented on 1. Process/process.hpp
> +    int fd_in, fd_out;
постфикс префикс

2020-10-09 18:55 UTC, a-badin commented on 1. Process/process.cpp
> +        size_t bytes_read = read(sized_data + offset, len);
read может вернуть 0, и тогда будет бесконечный цикл, надо проверить этот момент

2020-10-10 21:00 UTC, closed without merging

2020-10-10 21:14 UTC, Mr-S-Mirzoev commented
Closed by mistake

2020-10-10 21:23 UTC, Mr-S-Mirzoev commented
[New pull request](https://github.com/Mr-S-Mirzoev/TechnoSphere/pull/5)