Task3 develop
Mr-S-Mirzoev/TechnoSphere-Task pull request #11
Opened 2020-10-23 14:56 UTC by Mr-S-Mirzoev

2020-11-03 15:25 UTC, a-badin requested changes

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +        struct sockaddr_in *copy = std::static_cast <struct sockaddr_in>
У вас программа не могла компилироваться с такой ошибкой

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +    void Server::set_max_connection(unsigned max_connection=SOMAXCONN) noexcept {
дефолтные параметры указываются при первом **объявлении**

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/CMakeLists.txt
> +add_executable(${TARGET_NAME} ${TEST})
файлы тест пустые, сборка не собирается

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/CMakeLists.txt
> +target_include_directories(${LIB_NAME} PUBLIC ${INC_DIR})
Если вы заполните все команды относительно текущей директории (без LIB_DIR, LIB_NAME и INC_DIR) вы сможете добавлять эту библиотеку в любой проект простым add_subdirectory, а сейчас вам сначала нужно установить переменные

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.8)
Вот это объявляется один раз в корневом

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
И это тоже уже определно в корневом
Правило можно сказать такое:
Если стоит `cmake_minimum_required` и `project` - значит этот проект самостоятельный, можно вызвать cmake и собрать из этого файла
Если `cmake_minimum_required` и `project`  не стоят, значит это cmake подпроекта другого проекта и собрать его можно только через корневой cmake

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/address.hpp
> +        int _port;
если сделать 2 байта, не нужно будет обрабатывать ситуацию когда порт может выйти за рамки

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/address.hpp
> +        std::string _str_addr;
вам достаточно хранить что-то одно, вы можете получить из строки число и из числа строку.
Когда вы храните оба значения, вы увеличиваете шанс на потерю согласованности между этими значениями ( обновили численное, но забыли строковое, например)

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/address.hpp
> +        struct sockaddr_in _addr {};
struct нужно было писать в С, в С++ можно писать сразу `::sockaddr_in`

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/address.cpp
> +        ::inet_aton(s_addr.c_str(), &_addr.sin_addr);
нужно проверить на ошибку и убрать noexcept

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/address.cpp
> +    Address(): Address("127.0.0.1", 8888) {}
очень сомнительные значения, я думаю лучше не делать значений по-умолчанию совсем

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/address.cpp
> +    Address::Address(const Address &other) noexcept:
компилятор сделает его вам сам, если без noexcept

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/address.cpp
> +    Address::~Address() = default;
Что проще написать `Address::~Address() {}` или `Address::~Address() = default`?
Тогда зачем сделали  = default в С++11?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/descriptor.hpp
> +        Descriptor(Descriptor &) = delete;
const

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/descriptor.cpp
> +        _fd = fd;
Если до set он был открыт?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/descriptor.cpp
> +        _fd = other._fd;
А если до присваивания он был открыт?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/descriptor.cpp
> +        other._fd = -1;
Есть фокус, `_fd = std::exchange(other._fd, -1);`

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/descriptor.cpp
> +        return (_fd < 0);
а без скобок будет работать?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/address.hpp
> +#include <string>
оставить только необходимое для объявления

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/connection.hpp
> +        bool _is_set;  // if not connected restrict operations until "connect" is called
Чем больше у вас состояний объекта (число всех комбинаций всех членов данных класса), тем проще делать ошибки. Меньше состояний = проще их контролировать. Флаг _is_set полностью покрывается состоянием вашего Descriptor

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/connection.hpp
> +        Descriptor _d; // RAII class holding socket descriptor
плохое название переменной

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/connection.hpp
> +            as from the reason behind this class there cannot be two different connections
на самом деле не поэтому, как только у вас появляется возможность сделать копию, у вас 2 объекта контролируют 1 ресурс - дескриптор. Первый закроет, а второй закроет уже чужой дескриптор в деструкторе

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/connection.hpp
> +        void connect(Address address);
почему по значению

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/connection.hpp
> +#include <cstddef>
кажется не нужен

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/connection.hpp
> +};
namespace не закрываются через `;`, лучше закрывать комментарием // namespace tcp

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/exceptions.hpp
> +    class SocketClosed: public std::runtime_error {
В лекции 2 обсуждали как лучше создавать исключения для библиотек

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/exceptions.hpp
> +        explicit SocketClosed(std::string s = "read");
Давайте сделаем 2 отдельных

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/server.hpp
> +#define SOMAXCONN 2
Так можно переопределить системную константу - это очень опасно. Сделайте свою константу c типом

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/inc/socket.hpp
> +    class Socket {
Это нужно?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +    Connection::Connection(): _d(socket(AF_INET, SOCK_STREAM, 0)), _is_set(false) {}
Так вы множите число невалидных состояний: дескриптор есть, но он не подключен, адрес пустой. Плюс у вас резервируется дескриптор, но не используется (число дескрипторов в системе ограничено)

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +    Connection::Connection(const Address &addr): _addr(addr), _d(socket(AF_INET, SOCK_STREAM, 0)), _is_set(true) {}
Вот это стостояние совсем странное, адрес есть, дескриптор есть, флаг стоит, но полдьзоваться объектом нельзя - он не подключен

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        con._is_set = false;
а адрес у other остался, много состояний - много проблем

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        struct sockaddr_in *copy = new struct sockaddr_in (addr.get_struct());
на стеке

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        int ret_val = ::connect(_d.get_fd(),
создавайте дескриптор, когда он стал вам нужен. А когда все успешно создалось и подключилось замещайте его в _d

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        if (ret_val < 0)
никогда не выполнится

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +            throw SocketClosed();
вариант, но нужно помнить, что бросок исключения не бесплатно

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +            std::cerr << "Quantity of read bytes: " << ret_val << std::endl;
это что такое

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +            throw WriteFailed();
никогда не кинет

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        std::cerr << "Quantity of written bytes: " << ret_val << std::endl;
если это отладка, подключите вторую домашнюю работу и логируйте с уровнем DEBUG

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +            std::cerr << e.what() << std::endl;
Если я хочу в случае ошибки повторить чтение через 10 секунд, как мне это сделать?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +                std::cerr << "Data: " << std::string(data);
отладка - это хорошо, мы специально сделали удобную бибилотеку для этого

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +                std::cerr << "Data: " << std::string(data);
лучше std::string_view{data, bytes_written} - не будет копирования и не будет выводить закорючки, если выйдете за предел буфера

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        timeval timeout{.tv_sec = 5, .tv_usec = 0};
ms - это миллисекунды

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +                        SO_SNDTIMEO,
а на получение?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +            std::cerr << "Client connected at: " << new_client.to_string() << std::endl;
Какое значение теперь у new_d ?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +            return Connection(new_client, std::move(new_d));
Какое значение теперь у дескриптора Connection?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +            _clients.insert({new_client, std::move(new_d)});
Кто владеет ресурсом дескриптора,Server или Connection?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +            desc.close();
Как перестать принимать новые подключения не разрывая соединения с текущими?

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +                        SO_SNDTIMEO,
Серверный сокет не имеет функций для которых SO_SNDTIMEO имел бы смысл

2020-11-03 15:25 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +            std::cerr << "Set timeout error" << std::endl;
Как мне среагировать на эту ошибку в программе?

2020-11-04 22:41 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.8)
Но ведь на коммент выше мы хотим уйти от зависимости CMakeLists?

2020-11-04 22:42 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
В таком случае установил project в нижнем симэйк

2020-11-04 23:15 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/address.cpp
> +    Address::~Address() = default;
This is a new C++0x feature that tells the compiler to create the default version of the respective constructor or assignment operator, i.e. the one which just performs the copy or move action for each member.


~Address() {} содержит пустое тело, т.е хуже.

2020-11-04 23:19 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/descriptor.cpp
> +        other._fd = -1;
Классная штука)

2020-11-04 23:19 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/descriptor.cpp
> +        return (_fd < 0);
Да, по порядку приоритетов. Вопрос кодстайла, мне так приятнее глазу. Но хорошо, убрал)

2020-11-04 23:24 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/exceptions.hpp
> +    class SocketClosed: public std::runtime_error {
стоит пересмотреть тогда.

2020-11-04 23:28 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/socket.hpp
> +    class Socket {
Это - в смысле класс Socket?

2020-11-04 23:29 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/connection.cpp
> +    Connection::Connection(): _d(socket(AF_INET, SOCK_STREAM, 0)), _is_set(false) {}
Будет исправлено.

2020-11-04 23:31 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/server.cpp
> +            desc.close();
Закрыть слушающий сокет?

2020-11-04 23:31 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/server.cpp
> +            _clients.insert({new_client, std::move(new_d)});
Коннекшн

2020-11-06 20:21 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/address.hpp
> +        int _port;
Сделал

2020-11-06 20:23 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/connection.hpp
> +        void connect(Address address);
Странно, в моей локальной версии это уже исправлено)))

2020-11-06 20:25 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/connection.hpp
> +};
Исправил

2020-11-06 20:27 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/exceptions.hpp
> +    class SocketClosed: public std::runtime_error {
Так и не понял, что не так(( 
Насколько я помню, обсуждалось, что каждый класс должен иметь свои исключения: Дескриптор - исключения связанные с его функционалом, Адрес - исключения, связанные с его функционалом, итп

2020-11-06 20:27 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/exceptions.hpp
> +        explicit SocketClosed(std::string s = "read");
Это сделано

2020-11-06 20:27 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/server.hpp
> +#define SOMAXCONN 2
Хорошо, сделал

2020-11-06 21:15 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/socket.hpp
> +    class Socket {
Socket убрал

2020-11-06 21:22 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/connection.cpp
> +        struct sockaddr_in *copy = new struct sockaddr_in (addr.get_struct());
Fixed

2020-11-06 21:23 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/connection.cpp
> +        int ret_val = ::connect(_d.get_fd(),
Не совсем понял....

2020-11-06 21:31 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/connection.cpp
> +            throw SocketClosed();
Теперь в readExact проверяю. 3 последовательно полученные исключения - выбрасываю ReadFailed

2020-11-06 21:38 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/connection.cpp
> +            std::cerr << e.what() << std::endl;
Добавить такую опцию или это отсылка к чему-то?

2020-11-06 21:39 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/connection.cpp
> +                std::cerr << "Data: " << std::string(data);
подключу ее, как только солью 2е задание в мастер.

2020-11-06 21:45 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/server.cpp
> +            std::cerr << "Client connected at: " << new_client.to_string() << std::endl;
Невалидное, но разве это проблема?

2020-11-06 21:48 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/server.cpp
> +                        SO_SNDTIMEO,
Настроил для RCV

2020-11-07 06:38 UTC, a-badin requested changes

2020-11-07 06:38 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        struct sockaddr_in *copy = new struct sockaddr_in (addr.get_struct());
остается

2020-11-07 06:38 UTC, a-badin commented on 3. TCP Server/inc/server.hpp
> +        int _port;
unsinged short

2020-11-07 06:38 UTC, a-badin commented on 3. TCP Server/lib/address.cpp
> +    Address::Address(const ::sockaddr_in *struct_addr) noexcept:
reference

2020-11-07 06:38 UTC, a-badin commented on 3. TCP Server/inc/address.hpp
> +        ~Address() noexcept;
= defaut, noexcept идет по-умолчанию

2020-11-07 06:38 UTC, a-badin commented on 3. TCP Server/inc/address.hpp
> +        bool operator< (const Address &other) const noexcept;
-если не нужно убрать

2020-11-07 06:38 UTC, a-badin commented on 3. TCP Server/lib/address.cpp
> +        ::sockaddr_in remote = {0};
::sockaddr_in remote{};

2020-11-07 06:38 UTC, a-badin commented on 3. TCP Server/inc/address.hpp
> +        std::string _str_addr;
Что то одно удалить

2020-11-07 06:38 UTC, a-badin commented on 3. TCP Server/inc/descriptor.hpp
> +};
//

2020-11-07 06:38 UTC, a-badin commented on 3. TCP Server/inc/exceptions.hpp
> +};
//

2020-11-07 09:30 UTC, Mr-S-Mirzoev commented on 3. TCP Server/lib/address.cpp
> +    Address::Address(const ::sockaddr_in *struct_addr) noexcept:
https://github.com/Mr-S-Mirzoev/TechnoSphere/blob/0a3fed80fa31b3cd3fba50b067671289e180ef80/3.%20TCP%20Server/lib/address.cpp#L14

Already resolved

2020-11-07 09:31 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/address.hpp
> +        ~Address() noexcept;
https://github.com/Mr-S-Mirzoev/TechnoSphere/blob/0a3fed80fa31b3cd3fba50b067671289e180ef80/3.%20TCP%20Server/inc/address.hpp#L18

Already resolved

2020-11-07 09:34 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/address.hpp
> +        std::string _str_addr;
https://github.com/Mr-S-Mirzoev/TechnoSphere/blob/0a3fed80fa31b3cd3fba50b067671289e180ef80/3.%20TCP%20Server/inc/address.hpp#L11

Already resolved

2020-11-07 09:35 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/descriptor.hpp
> +};
https://github.com/Mr-S-Mirzoev/TechnoSphere/blob/0a3fed80fa31b3cd3fba50b067671289e180ef80/3.%20TCP%20Server/inc/descriptor.hpp#L25

Already resolved

2020-11-07 09:35 UTC, Mr-S-Mirzoev commented on 3. TCP Server/inc/exceptions.hpp
> +};
https://github.com/Mr-S-Mirzoev/TechnoSphere/blob/0a3fed80fa31b3cd3fba50b067671289e180ef80/3.%20TCP%20Server/inc/exceptions.hpp#L94

Already resolved

2020-11-09 14:18 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +#define SOMAXCONN	4096
Лучше не пользоваться define'ами В С++11 появились constexpr - они не теряют тип

2020-11-09 14:18 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +    Connection::Connection(const Address &addr): _addr(addr), _sock(socket(AF_INET, SOCK_STREAM, 0)) {}
Все же не понимаю, зачем резервировать сокет под непроинициализированный объект. Оставьте его пустым - у вас тогда будет 2 состояния или ничего нет, или все есть, все уставновлено, соединено и можно работать

2020-11-09 14:18 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        if (ret_val == 0)
А если -1? Ошибка может быть - может
У вас тип ret_val беззнаковый, он не может быть < 0. Ошибка была в типе выбранном для ret_val

2020-11-09 14:18 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +                    if (count == 3)
Это не вы должны навязывать свою логику, если пользователь не хочет делать 3 попытки, если он хочет сделать 4? Кидайте исключение пользователь решит, что делать в этом случае

2020-11-09 14:18 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        size_t ret_val = ::write(_sock.get_fd(), data, buf_len);
обработать ошибку надо

2020-11-09 14:18 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +            std::cerr << e.what() << std::endl;
Это отсылка к тому, что нужно кидать исчлючение, а не пытаться придумать универсальную логику обработки ошибки на все случаи жизни

2020-11-09 14:38 UTC, a-badin requested changes

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        timeval timeout{.tv_sec = 5, .tv_usec = 0};
почему 5

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +            ::sockaddr_in copy {0};
{};

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +        timeval timeout{.tv_sec = 0, .tv_usec = ms};
tv_usec - это микросекунды

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/CMakeLists.txt
> +set(DEFAULT_PORT 60606)
Вот это очень сильно - компилировать программу заново чтобы поменять порт

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/inc/exceptions.hpp
> +    std::string last_error();
Глобальное состояние - всегда плохо

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/inc/server.hpp
> +    const unsigned default_max_connection_count = 100;
константы обычно пишутся с заглаными буквами
Для скаляров лучше вместо const писать constexpr

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/inc/server.hpp
> +        uint16_t _port;
почему не хранить адрес

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/inc/server.hpp
> +        Server(int port, unsigned max_con = default_max_connection_count);
для сервера адрес тоже имеет значение

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        ::shutdown(_sock, SHUT_RD);
raii сделает это все за вас, shutdown используется только если нужно закрывать только пол дуплекса

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +    Server::Server(int port, unsigned max_con): _listen_socket(std::move(create_inet4_socket())),
что делает std::move?

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +        } catch (...) {
Так лучше не делать

2020-11-09 14:38 UTC, a-badin commented on 3. TCP Server/lib/server.cpp
> +        _max_con = max_connection;
Потеря базовой гарантии безопасности исключений

2020-11-10 15:00 UTC, a-badin requested changes

2020-11-10 15:00 UTC, a-badin commented on 3. TCP Server/lib/connection.cpp
> +        return (bool(_sock));
`static_cast<bool>(_sock)`

2020-11-10 15:00 UTC, a-badin commented on 3. TCP Server/lib/descriptor.cpp
> +        return std::move(Descriptor(sock_no));
Что делает std::move ?

2020-11-13 17:39 UTC, a-badin approved these changes

2020-11-15 09:01 UTC, merged

2020-11-17 15:46 UTC, a-badin commented
Засчитываю на 8