Task1 develop
Mr-S-Mirzoev/TechnoSphere-Task pull request #5
Opened 2020-10-10 21:21 UTC by Mr-S-Mirzoev

Previous pull-request was closed by mistake, during git push --force origin

2020-10-13 14:07 UTC, a-badin requested changes
Если вы хотите менять поведение программы в зависимости от архитектуры или платформы - лучше сделать это так: например, у вас есть заголовочный файл с сигнатурой pipe2(...), а реализацию у вас выбирает система сборки (cmake) в зависимости от неё вы компилируете, например, pipe2_win32_impl.cpp 
или pipe2_macos_impl.cpp. С макросами препроцессора код сильно теряет читабельность

2020-10-13 14:07 UTC, a-badin commented on filter.sh
> +git filter-branch --env-filter '
Можно установить локальный для репозитория конфиг имени и почты
```
git config --local user.name "FIRST_NAME LAST_NAME"
git config --local user.email "foo@bar.com"
```

2020-10-13 14:07 UTC, a-badin commented on 1. Process/ostype.hpp
> +enum OS {
Что-то мне совершенно не хочется в этом разбираться

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +#if PLATFORM_ENUM == OS_OSX
Если так вышло, что у вас в mac os не поддерживается pipe2, сделайте одну общую реализацию через fcntl и pipe

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +        kill(_pid, SIGINT);
waitpid

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +    if (!is_child(_pid)) {
Распишите в каком сценарии программа окажется в этой точке с _pid == 0

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +std::vector<char*> arg_list(const std::string &name, const std::vector <std::string>& args) {
напишите, что делает анонимное пространство имен

2020-10-13 14:07 UTC, a-badin commented on 1. Process/main.cpp
> +    std::cout << s;
Вывод ps.read(s.data(), 1000); нужно запомнить и сделать s.resize() на эту величину.

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +    cstyle_args.push_back(const_cast<char*>(name.c_str()));
Лучше не пользоваться const_cast'ом, мы будем разбирать случаи, когда const_cast может привести к SEGFAULT. Сделайте локальную копию std::vector <std::string> снаружи функции

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +        kill(_pid, SIGKILL);
waitpid, ведь fork прошел - значит процесс породился и сейчас находится в состоянии зомби

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +    bool _noexec = (pid_result != 0);
имя без _

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +    //::close(fd2[1]);
Зачем, это нужный код

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +    if (POSIX_ERROR(fcntl(_fd_in, F_GETFD)))
Эта логика не может проверить, что _fd_in не закрыт со стороны дочернего процесса

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.cpp
> +#ifdef DEBUG
Лучше вынести в отдельную функцию, очень тяжело читать такие вставки
Лучше полагаться на NDEBUG для релиза, потому что этот макрос стандартизирован. Тогда cmake сам определит его для релизной сборки

2020-10-13 14:07 UTC, a-badin commented on 1. Process/process.hpp
> +#define DEBUG
Такие вещи лучше определять в конфигурации сборки, тогда у вас будет возможность держать сразу и релизную и отладочную сборку без необходимости менять исходники

2020-10-13 14:19 UTC, Mr-S-Mirzoev commented on 1. Process/process.cpp
> +    if (!is_child(_pid)) {
Справедливо, ни в каком, т.к. контекст для порожденного процесса полностью заменится после exec.

2020-10-13 21:15 UTC, Mr-S-Mirzoev commented on 1. Process/process.cpp
> +std::vector<char*> arg_list(const std::string &name, const std::vector <std::string>& args) {
Делает то же, что и static: делает данную функцию локальной для данного пространства имен (то есть если в другом cpp файле будет такая же функция, ошибки линковки не будет)

2020-10-13 21:20 UTC, Mr-S-Mirzoev commented on 1. Process/process.cpp
> +    cstyle_args.push_back(const_cast<char*>(name.c_str()));
Не очень понимаю альтернативную реализацию, предлагаемую Вами

2020-10-13 21:25 UTC, Mr-S-Mirzoev commented on 1. Process/process.cpp
> +    if (POSIX_ERROR(fcntl(_fd_in, F_GETFD)))
Но ведь проверка, закрыт ли _fd_in со стороны дочернего процесса может быть проверена только при попытке read, там и проверяется. Или я заблуждаюсь?

2020-10-13 21:30 UTC, Mr-S-Mirzoev commented on 1. Process/process.cpp
> +#ifdef DEBUG
Что означает cmake сам его определит для релизной сборки? Вынести в отдельную функцию дебажные выводы в std::cerr? Если так, то хорошо, это просто делается.

2020-10-15 08:19 UTC, a-badin requested changes
Остались ifdef DEBUG остались
is_child остался, хотя мы выяснили что 0 он быть не может.
Разобрались зачем нужен static, но нигде его так и не применили

2020-10-15 08:19 UTC, a-badin commented on 1. Process/process.cpp
> +std::vector<char*> arg_list(const std::string &name, const std::vector <std::string>& args) {
Ну так почему бы её не сделать такой, если её в заголовочном файле нет.

2020-10-18 10:47 UTC, a-badin requested changes

2020-10-18 10:47 UTC, a-badin commented on 1. Process/process.cpp
> +    return cstyle_args;
У вас в cstyle_args лежат указатели на строки, которые умрут сразу после return. Потому что args_copy и name_copy лежат на стеке.

Я вам написал "Если вы хотите эту логику перенести в какую-нибудь отдельную функцию, то нужно убедиться, что copy переживет raw_args, не уничтожится раньше"

2020-10-18 10:47 UTC, a-badin commented on 1. Process/process.cpp
> +    if (POSIX_ERROR(fcntl(_fd_out, F_GETFD)))
Мы с вами разобрались, что этот код вам ничего не даёт.

Это дорогая, менее понятная и избыточная проверка на _fd_out != -1

2020-10-18 13:28 UTC, Mr-S-Mirzoev commented on 1. Process/process.cpp
> +    if (POSIX_ERROR(fcntl(_fd_out, F_GETFD)))
Потерял этот пункт, когда исправлял. Подправлю, прошу прощения.

2020-10-18 19:05 UTC, Mr-S-Mirzoev commented on 1. Process/process.cpp
> +    return cstyle_args;
Убрал данную логику, получаю лист аргументов перед execvp

2020-10-18 19:06 UTC, Mr-S-Mirzoev commented on 1. Process/process.cpp
> +    if (POSIX_ERROR(fcntl(_fd_out, F_GETFD)))
Исправил на _fd_out == -1

2020-10-20 15:34 UTC, a-badin commented on 1. Process/process.cpp
> +    return cstyle_args;
Зачем тогда оставили функцию. Вы могли оставить функцию, только надо было тогда аргументы передавать по non-const ссылке. И передавать туда ваши копии

2020-10-20 15:34 UTC, a-badin commented on 1. Process/process.cpp
> +    if (POSIX_ERROR(fcntl(_fd_out, F_GETFD)))
В принципе даже это лишнее, write все равно вернет < 0

2020-10-20 15:34 UTC, a-badin approved these changes

2020-10-20 15:35 UTC, merged