Task2 develop
Mr-S-Mirzoev/TechnoSphere-Task pull request #9
Opened 2020-10-15 23:27 UTC by Mr-S-Mirzoev

2020-10-21 16:44 UTC, Kapitonov requested changes

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/CMakeLists.txt
> +add_executable(main main.cpp log_utils.cpp logger.cpp file.cpp stdstream.cpp base.cpp tools.cpp)
Надо вынести в отделбную библтиотеку и подключать библиотеку, а не отдельные файлы.

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/base.hpp
> +        std::vector <Message> _text_log;
Надо либо сразу писать, либо писать каждые n сообщений

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/base.hpp
> +        virtual ~BaseLogger();
Второй раз определн деструктор.

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/base.hpp
> +        static std::unique_ptr<BaseLogger> _ptr;
Нет заголовка memory для указателя

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/file.cpp
> +            if (_level.allowed(val.get_level())) {
Вы звписывали в сообщения уровень, но сравниваете его с текущим уровнем, он может не соответсвовать уровню который был на момент записи в лог. Так вы запишите лишнее или потеряете сообщения.

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/base.hpp
> +        void log(const std::string &message, Level level);
По заданию, это приватная функция

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/log_utils.cpp
> +        auto logger = log::Logger::get_instance();
А зачем переменная, не лучше одной строкой?

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/stdstream.cpp
> +    StdErrLogger::StdErrLogger() {
Надо разнести по разным файлам.

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/inc/base.hpp
> +        static std::unique_ptr<BaseLogger> _ptr;
Зачем, это же не синглтон.

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/inc/base.hpp
> +    class BaseLogger {
все ваши потоки вывода унаследованны от std::ostream, предлагаю это как-то заиспользовать, тогда методы flush и log можно перенести в BaseLogger и не дублировать код.

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/inc/tools.hpp
> +        QUANTITY // The constant to know  now many levels do we have
Странные и не совсем нужные переменные.

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/inc/tools.hpp
> +        NIL, // Nil value to define an error in passed Level Number
Лучше инициализировать по умолчанию каким-то значением, например ERROR

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/inc/logger.hpp
> +        static void set_global_logger(BaseLogger *other);
Лучше передавать по значению, чтобы я не смог внешне удалить элемент . Что повлечет к segmentation fault.

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/inc/tools.hpp
> +        level_t to_int () const;
почему функция to_int, а значение level_t?

2020-10-21 16:44 UTC, Kapitonov commented on 2. Logger/inc/tools.hpp
> +        std::string to_string() const;
Эту функцию лучше заменить на прямое использоване значенией строк в методах debug, info, ... . Тогда класс можно убрать и использовать только enum

2020-10-22 22:58 UTC, Mr-S-Mirzoev commented on 2. Logger/inc/logger.hpp
> +        static void set_global_logger(BaseLogger *other);
не очень понимаю, ка это сделать. Вернее, каку альтернативу Вы предлагаете

2020-10-25 10:44 UTC, Kapitonov requested changes

2020-10-25 10:44 UTC, Kapitonov commented on 2. Logger/README.md
> +    │   ├── CMakeLists.txt - Shared library linker
Обычно папка с CMakeLists содержит папку src и уже в ней код библиотеки.

2020-10-25 10:44 UTC, Kapitonov commented on 2. Logger/inc/base.hpp
> +        virtual void flush() = 0;
Имея указатель на ostream можно реализовать flush  в BaseLogger.

2020-10-25 10:44 UTC, Kapitonov commented on 2. Logger/inc/logger.hpp
> +        static void set_global_logger(BaseLogger *other);
Передавать unique_ptr\<BaseLogger\> other

2020-10-25 10:44 UTC, Kapitonov commented on 2. Logger/lib/logger.cpp
> +    std::unique_ptr<Logger> Logger::_instance {nullptr};
Это же синглтон, зачем это?

2020-10-25 10:44 UTC, Kapitonov commented on 2. Logger/inc/base.hpp
> +        static bool _instanceFlag;
Где-то используется?

2020-11-06 17:13 UTC, Kapitonov requested changes

2020-11-06 17:13 UTC, Kapitonov commented on 2. Logger/lib/src/file.cpp
> +        flush();
Flush делать не надо, его сделает деструктор ofstream

2020-11-06 17:13 UTC, Kapitonov commented on 2. Logger/lib/src/log_utils.cpp
> +        std::ofstream outFile(path);
Не надо, ваш конструктор может принимать строку.

2020-11-06 17:13 UTC, Kapitonov commented on 2. Logger/lib/src/log_utils.cpp
> +        log::Logger::get_instance()->set_global_logger(ptr); // noexcept
make_unique

2020-11-06 17:13 UTC, Kapitonov commented on 2. Logger/inc/logger.hpp
> +        static Logger* get_instance();
Добавить константность ссылкам.

2020-11-06 17:13 UTC, Kapitonov commented on 2. Logger/lib/src/stderr.cpp
> +        flush();
Он ничего не делает.

2020-11-07 09:49 UTC, Mr-S-Mirzoev commented on 2. Logger/inc/logger.hpp
> +        static Logger* get_instance();
Ссылка не м.б. константной, т.к. имеем метод set_level - неконстантный

2020-11-11 23:30 UTC, Kapitonov requested changes

2020-11-11 23:30 UTC, Kapitonov commented on 2. Logger/inc/logger.hpp
> +        static Logger* get_instance();
Надо сделать константным указатель, а не константное значение.

2020-11-11 23:30 UTC, Kapitonov commented on 2. Logger/inc/base.hpp
> +        static std::unique_ptr<BaseLogger> _ptr;
Ещё не исправлено.

2020-11-13 17:22 UTC, Kapitonov requested changes

2020-11-13 17:22 UTC, Kapitonov commented on 2. Logger/lib/src/logger.cpp
> +    std::unique_ptr<BaseLogger> Logger::_global_logger {nullptr};
Перенести в конструктор.

2020-11-13 17:22 UTC, Kapitonov commented on 2. Logger/inc/logger.hpp
> +        static std::unique_ptr<BaseLogger> _global_logger;
Не надо статик.

2020-11-19 02:10 UTC, Kapitonov commented
Почините конфликт и сливайте.

2020-11-20 05:34 UTC, merged